In [5]:
import pandas as pd
import numpy as np
from pathlib import Path

from sentence_transformers import SentenceTransformer

ROOT = Path.cwd().parent
print(ROOT)

DATA_RAW = ROOT/"data/processed"

INPUT_PATH = DATA_RAW / "the_numbers_plot_franchise.csv"
OUTPUT_PATH = DATA_RAW / "00_descr_title_df.csv"

model_df = scrape_df = pd.read_csv(INPUT_PATH)

/workspaces/BoxOffice-Oracle/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

/workspaces/BoxOffice-Oracle

In [12]:
model_df["plot_summary"].notna().mean()

np.float64(0.7085492227979274)

In [29]:
sample_df=model_df[model_df["plot_summary"].notna()]

In [16]:
import re

def remove_title_from_plot(row):
    title = str(row["primaryTitle"])
    plot = str(row["plot_summary"])

    if not title or not plot:
        return plot

    pattern = re.escape(title)
    cleaned = re.sub(pattern, "", plot, flags=re.IGNORECASE)

    return re.sub(r"\s+", " ", cleaned).strip()

sample_df["plot_summary_no_title"] = sample_df.apply(
    remove_title_from_plot,
    axis=1
)

In [19]:
# Load small embedding model
embedder = SentenceTransformer("all-MiniLM-L6-v2")

# Fill missing text with empty string
plot_texts = sample_df["plot_summary_no_title"].fillna("").astype(str).tolist()

# Create embeddings
plot_embeddings = embedder.encode(
    plot_texts,
    batch_size=32,
    show_progress_bar=False, #Need to download extra stuff for it
    normalize_embeddings=True
)

plot_embeddings.shape

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 10568.36it/s]

(1641, 384)

In [20]:
# Fill missing text with empty string
title_texts = sample_df["primaryTitle"].fillna("").astype(str).tolist()

# Create embeddings
title_embeddings = embedder.encode(
    title_texts,
    batch_size=32,
    show_progress_bar=False, #Need to download extra stuff for it
    normalize_embeddings=True
)

title_embeddings.shape

(1641, 384)

In [22]:
sample_df["title_plot_similarity"] = np.sum(
    title_embeddings * plot_embeddings,
    axis=1
)

In [23]:
sample_df.head()

,tconst,primaryTitle,startYear,the_numbers_url,scrape_success,scrape_error,plot_summary,franchise,has_plot_summary,title_plot_similarity,plot_summary_no_title
0,tt0120667,Fantastic Four,2005.0,https://www.the-numbers.com/movie/Fantastic-Fo...,True,NaN,Scientist Reed Richards persuades his arrogant...,Fantastic Four,True,0.217350,Scientist Reed Richards persuades his arrogant...
2,tt0121766,Star Wars: Episode III - Revenge of the Sith,2005.0,https://www.the-numbers.com/movie/Star-Wars-Ep...,True,NaN,"Years after the onset of the Clone Wars, the n...",Star Wars,True,0.473704,"Years after the onset of the Clone Wars, the n..."
4,tt0200465,The Bank Job,2008.0,https://www.the-numbers.com/movie/Bank-Job-The,True,NaN,Self-reformed petty criminal Terry Leather has...,NaN,True,0.257784,Self-reformed petty criminal Terry Leather has...
5,tt0204313,Exorcist: The Beginning,2004.0,https://www.the-numbers.com/movie/Exorcist-The...,True,NaN,Father Lankester Merrin lost his faith after t...,Exorcist,True,0.143046,Father Lankester Merrin lost his faith after t...
10,tt0257516,Cursed,2005.0,https://www.the-numbers.com/movie/Cursed,True,NaN,"In Los Angeles, siblings Ellie and Jimmy come ...",NaN,True,0.248333,"In Los Angeles, siblings Ellie and Jimmy come ..."

In [24]:
sample_df[
    [
        "primaryTitle",
        "plot_summary",
        "title_plot_similarity"
    ]
].sort_values(
    "title_plot_similarity",
    ascending=False
).head(20)

,primaryTitle,plot_summary,title_plot_similarity
1205,Mr. Popper's Penguins,"In this family comedy, Mr. Popper, is a driven...",0.833349
806,The Adventures of Tintin,Tintin is a young reporter whose relentless pu...,0.804434
1231,Hansel & Gretel: Witch Hunters,"After getting a taste for blood as children, H...",0.786131
1939,Godzilla: King of the Monsters,An action adventure that pits Godzilla against...,0.777971
1042,Rambo: Last Blood,"Almost four decades after he drew first blood,...",0.771783
2275,Kraven the Hunter,Kraven is a man whose complex relationship wit...,0.755683
1471,Horizon: An American Saga - Chapter 1,Horizon: An American Saga explores the lure of...,0.749925
1254,Godzilla X Kong: The New Empire,This latest entry follows up the explosive sho...,0.749787
146,"The Chronicles of Narnia: The Lion, the Witch ...",Four young adventurers playing hide and-seek i...,0.746720
2301,Shang-Chi and the Legend of the Ten Rings,Shang-Chi must confront the past he thought he...,0.744656
1144,Mufasa: The Lion King,"Mufasa is an orphaned cub, lost and alone unti...",0.739918
2213,Teen Titans GO! To the Movies,"When the Teen Titans go to the big screen, the...",0.735746
1730,Smurfs: The Lost Village,A mysterious map sets Smurfette and her best f...,0.732539
2041,The Curse of La Llorona,La Llorona. The Weeping Woman. A horrifying ap...,0.731812
2224,A Dog's Way Home,A Dog’s Way Home chronicles the heartwarming a...,0.718932
1613,Paranormal Activity 4,The next sequel in the Paranormal Activity fra...,0.715306
1118,Cats & Dogs: The Revenge of Kitty Galore,"In the eternal battle between cats and dogs, o...",0.713561
1027,The Bourne Legacy,The Bourne Legacy pulls back the curtain to ex...,0.710556
2188,Resident Evil: Welcome to Raccoon City,Once the booming home of ​pharmaceutical giant...,0.705642
1165,The Pope's Exorcist,Inspired by the actual files of Father Gabriel...,0.701197

In [30]:
sample_df["franchise"].notna().mean()

np.float64(0.3583180987202925)

In [31]:
full_df = pd.read_csv(
    DATA_RAW/"the_numbers_model_base_v1.csv"
)

In [37]:
descr_title_df = full_df.merge(sample_df[["tconst","plot_summary","title_plot_similarity","franchise"]],how='inner',on="tconst")

In [39]:
descr_title_df["title_word_count"] = (
    descr_title_df["primaryTitle"]
    .fillna("")
    .str.split()
    .str.len()
)

descr_title_df["title_char_count"] = (
    descr_title_df["primaryTitle"]
    .fillna("")
    .str.len()
)

In [40]:
descr_title_df.sort_values(
    "title_plot_similarity",
    ascending=False
).head(20)

,tconst,primaryTitle,startYear,the_numbers_url,scrape_success,scrape_error,opening_weekend_gross,opening_theaters,domestic_release_date,release_type,...,legs,plot_point,raw_opening_weekend_text,raw_theater_counts_text,raw_domestic_releases_text,plot_summary,title_plot_similarity,franchise,title_word_count,title_char_count
570,tt1396218,Mr. Popper's Penguins,2011.0,https://www.the-numbers.com/movie/Mr-Poppers-P...,True,NaN,18445355.0,3339.0,2011-06-17,Wide,...,3.70,"Dysfunctional Family, Inheritance, Mid-Life Cr...","$18,445,355 (27.0% of total gross)","3,339 opening theaters/3,342 max. theaters, 4....","June 17th, 2011 (Wide) by 20th Century Fox, re...","In this family comedy, Mr. Popper, is a driven...",0.840938,NaN,3,21
728,tt1611224,Abraham Lincoln: Vampire Hunter,2012.0,https://www.the-numbers.com/movie/Abraham-Linc...,True,NaN,16306974.0,3108.0,2012-06-22,Wide,...,2.30,"Alternate History, Vampire, Young Child Dealin...","$16,306,974 (43.5% of total gross)","3,108 opening theaters/3,109 max. theaters, 3....","June 22nd, 2012 (Wide) by 20th Century Fox",Abraham Lincoln: Vampire Hunter brings to the ...,0.824134,NaN,4,31
1371,tt5090568,Transformers: Rise of the Beasts,2023.0,https://www.the-numbers.com/movie/Transformers...,True,NaN,61045464.0,3678.0,2023-06-09,Wide,...,2.58,Robot,"$61,045,464 (38.8% of total gross)","3,678 opening theaters/3,680 max. theaters, 5....","June 9th, 2023 (Wide) by Paramount Pictures Ju...",Returning to the action and spectacle that hav...,0.820709,Transformers,5,32
719,tt1598822,New Year's Eve,2011.0,https://www.the-numbers.com/movie/New-Years-Eve,True,NaN,13019180.0,3505.0,2011-12-09,Wide,...,4.19,"Coming of Age, Romance","$13,019,180 (23.9% of total gross)","3,505 opening theaters/3,505 max. theaters, 4....","December 9th, 2011 (Wide) by Warner Bros.","""New Year's Eve"" celebrates love, hope, forgiv...",0.813127,Garry Marshall's Holiday Franchise,3,14
153,tt0458339,Captain America: The First Avenger,2011.0,https://www.the-numbers.com/movie/Captain-Amer...,True,NaN,65058524.0,3715.0,2011-07-22,Wide,...,2.72,"Good vs. Evil, Nazis, Non-Chronological, Occul...","$65,058,524 (36.8% of total gross)","3,715 opening theaters/3,715 max. theaters, 5....","July 22nd, 2011 (Wide) by Paramount Pictures",Captain America: The First Avenger will focus ...,0.805694,Captain America,5,34
288,tt0983193,The Adventures of Tintin,2011.0,https://www.the-numbers.com/movie/Adventures-o...,True,NaN,9720993.0,3087.0,2011-12-21,Wide,...,6.78,"Addiction, Pirates, Treasure Hunters, Twins","$9,720,993 (12.5% of total gross)","3,087 opening theaters/3,087 max. theaters, 4....","December 21st, 2011 (Wide) by Paramount Pictur...",Tintin is a young reporter whose relentless pu...,0.804434,Tintin,4,24
794,tt1702443,Justin Bieber: Never Say Never,2011.0,https://www.the-numbers.com/movie/Justin-Biebe...,True,NaN,29514054.0,3105.0,2011-02-09,Wide,...,2.47,"Musicians, Non-Chronological","$29,514,054 (40.4% of total gross)","3,105 opening theaters/3,118 max. theaters, 4....","February 9th, 2011 (Special Engagement) by Par...",Justin Bieber: Never Say Never is the inspirin...,0.803139,NaN,5,30
242,tt0829150,Dracula Untold,2014.0,https://www.the-numbers.com/movie/Dracula-Untold,True,NaN,23514615.0,2887.0,2014-10-10,Wide,...,2.38,"Faustian, Monster, Origin Story, Vampire","$23,514,615 (42.0% of total gross)","2,887 opening theaters/2,900 max. theaters, 4....","October 10th, 2014 (Wide) by Universal October...",Dracula Untold is the origin story of the man ...,0.793902,Dark Universe,2,14
593,tt1428538,Hansel & Gretel: Witch Hunters,2013.0,https://www.the-numbers.com/movie/Hansel-and-G...,True,NaN,19690956.0,3372.0,2013-01-25,Wide,...,2.83,"Bounty Hunter, Corrupt Cops, Non-Chronological...","$19,690,956 (35.3% of total gross)","3,372 opening theaters/3,375 max. theaters, 4....","January 25th, 2013 (Wide) by Paramount Picture...","After getting a taste for blood as children, H...",0.786131,NaN,5,30
14,tt0320661,Kingdom of Heaven,2005.0,https://www.the-numbers.com/movie/Kingdom-of-H...,True,NaN,19635996.0,3216.0,2005-05-06,Wide,...,2.42,"Christians, The Crusades, Middle East, Muslims...","$19,635,996 (41.3% of total gross)","3,216 opening theaters/3,219 max. theaters, 3....","May 6th, 2005 (Wide) by 20th Century Fox May 1...",Kingdom of Heaven is an epic adventure about a...,0.785196,NaN,3,17
154,tt0458481,Sin City: A Dame to Kill For,2014.0,https://www.the-numbers.com/movie/Sin-City-A-D...,True,NaN,6317683.0,2894.0,2014-08-22,Wide,...,2.18,"Faulty Memory, Gambling, Government Corruption...","$6,317,683 (45.9% of total gross)","2,894 opening theaters/2,894 max. theaters, 2....","August 22nd, 2014 (Wide) by Weinstein Co.",Weaving together two of Miller's classic stori...,0.781842,Sin City,7,28
1252,tt3741700,Godzilla: King of the Monsters,2019.0,https://www.the-numbers.com/movie/Godzilla-Kin...,True,NaN,47776293.0,4108.0,2019-05-31,Wide,...,2.31,Creature Feature,"$47,776,293 (43.2% of total gross)","4,108 opening theaters/4,108 max. theaters, 4....","May 31st, 2019 (Wide) by Warner Bros. May 31st...",An action adventure that pits Godzilla against...,0.777971,Godzilla,5,30
428,tt1194173,The Bourne Legacy,2012.0,https://www.the-numbers.com/movie/Bourne-Legac...,True,NaN,38142825.0,3745.0,2012-08-10,Wide,...,2.97,"Government Corruption, Secret Agent","$38,142,825 (33.7% of total gross)","3,745 opening theaters/3,753 max. theaters, 6....","August 10th, 2012 (Wide) by Universal",The Bourne Legacy pulls back the curtain to ex...,0.774961,Bourne,3,17
1020,tt2304771,Mandela: Long Walk to Freedom,2013.0,https://www.the-numbers.com/movie/Mandela-Long...,True,NaN,84283.0,4.0,2013-11-29,Limited,...,3.71,"Bigotry, Biography, Government Corruption, Pol...","$84,283 (1.0% of total gross)","4 opening theaters/1,010 max. theaters, 2.9 we...","November 29th, 2013 (Limited) by Weinstein Co.",Mandela: Long Walk to Freedom celebrates Nelso...,0.774865,NaN,5,29
968,tt2177771,The Monuments Men,2014.0,https://www.the-numbers.com/movie/Monuments-Me...,True,NaN,22003433.0,3083.0,2014-02-07,Wide,...,3.55,"Museum, Nazis","$22,003,433 (28.2% of total gross)","3,083 opening theaters/3,083 max. theaters, 6....","February 7th, 2014 (Wide) by Sony Pictures",Based on the true story of the greatest treasu...,0.773191,NaN,3,17
438,tt1206885,Rambo: Last Blood,2019.0,https://www.the-numbers.com/movie/Rambo-Last-B...,True,NaN,18872919.0,3618.0,2019-09-20,Wide,...,2.37,"Ex-soldier, One Last Job, Revenge, The Past Ca...","$18,872,919 (42.1% of total gross)","3,618 opening theaters/3,618 max. theaters, 3....","September 20th, 2019 (Wide) by Lionsgate","Almost four decades after he drew first blood,...",0.771783,Rambo,3,17
430,tt1196141,Diary of a Wimpy Kid,2010.0,https://www.the-numbers.com/movie/Diary-of-a-W...,True,NaN,22126166.0,3077.0,2010-03-19,Wide,...,2.89,"Dysfunctional Family, New Guy/Girl in School, ...","$22,126,166 (34.6% of total gross)","3,077 opening theaters/3,083 max. theaters, 6....","March 19th, 2010 (Wide) by 20th Century Fox",Diary of a Wimpy Kid chronicles the adventures...,0.770009,Diary of a Wimpy Kid,5,20
914,tt1991245,Chernobyl Diaries,2012.0,https://www.the-numbers.com/movie/Chernobyl-Di...,True,NaN,7955307.0,2433.0,2012-05-25,Wide,...,2.28,"Cannibalism, Ghost Town, Mutants, Surprise Twi...","$7,955,307 (43.9% of total gross)","2,433 opening theaters/2,433 max. theaters, 2....","May 25th, 2012 (Wide) by Warner Bros.",Chernobyl Diaries follows a group of six young...,0.768265,NaN,2,17
727,tt1609486,Harold and the Purple Crayon,2024.0,https://www.the-numbers.com/movie/Harold-and-t...,True,NaN,6003197.0,3325.0,2024-08-02,Wide,...,2.94,NaN,"$6,003,197 (34.0% of total gross)","3,325 opening theaters/3,325 max. theaters, 2....","August 2nd, 2024 (Wide) by Sony Pictures","Inside of his book, adventurous Harold can mak...",0.766947,NaN,5,28
1286,tt4154796,Avengers: Endgame,2019.0,https://www.the-numbers.com/movie/Avengers-End...,True,NaN,357115007.0,4662.0,2019-04-26,Wide,...,2.40,"Alternate or Altered Realities, Death of a Bes...","$357,115,007 (41.6% of total gross)","4,662 opening theaters/4,662 max. theaters, 8....","April 26th, 2019 (Wide) by Walt Disney April 2...",The grave course of events set in motion by Th...,0.759745,Marvel Cinematic Universe,2,17

In [41]:
descr_title_df.to_csv(
    OUTPUT_PATH,
    index=False
)